### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by joe-bowman** [vegaprotocol/ethereum-event-forwarder#15]
Running eef from the docker container provided, as per the example config, I get the following error:

```
Error: 7 PERMISSION_DENIED: PermissionDenied error
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 7,
  details: 'PermissionDenied error',
  metadata: Metadata {
    internalRepr: Map(2) {
      'content-type' => [ 'application/grpc' ],
      'grpc-status-details-bin' => [
        Buffer(95) [Uint8Array] [
            8,   7,  18,  22,  80, 101, 114, 109, 105, 115, 115, 105,
          111, 110,  68, 101, 110, 105, 101, 100,  32, 101, 114, 114,
          111, 114,  26,  67,  10,  36, 116, 121, 112, 101,  46, 103,
          111, 111, 103, 108, 101,  97, 112, 105, 115,  46,  99, 111,
          109,  47, 118, 101, 103,  97,  46,  69, 114, 114, 111, 114,
           68, 101, 116,  97, 105, 108,  18,  27,   8, 144,  78,  18,
           22, 112, 117,  98, 107, 101, 121,  32, 110, 111, 116,  32,
           97, 108, 108, 111, 119, 108, 105, 115, 116, 101, 100
        ]
      ]
    },
    options: {}
  }
}
```

**Comment by jeremyletang** [comment]
This is an error returned by the node. While the error is indeed not looking great, this happen only in the case that the ethereum event forwarder public key is not AllowListed in the vega config section of the EvtForwarder.

**Comment by fkbenjamin** [comment]
@joe-bowman If you have a `0x` prefix in your `BlockchainQueueAllowlist` config, try removing it. That helped for me during the current testnet reset.
