### ISSUE TITLE
TimeoutError 

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/ethereum-event-forwarder#6]
The app should catch all errors, wait, retry, and if at all possible, not die.

```
$ docker logs ethereumeventforwarder 
{"level":30,"time":1630944876326,"pid":7,"hostname":"n01-d","msg":"Starting"}
{"level":30,"time":1630944876327,"pid":7,"hostname":"n01-d","msg":"Using primary config file '/eef/config.toml'"}
{"level":30,"time":1630944876327,"pid":7,"hostname":"n01-d","msg":"LOG_LEVEL: info"}
{"level":30,"time":1630944876328,"pid":7,"hostname":"n01-d","msg":"Connecting to Vega GRPC on '127.0.0.1:3002'"}
{"level":30,"time":1630944876345,"pid":7,"hostname":"n01-d","msg":"Using public key: '874c00168b302bc618e4a67126b8189c46a0b72ba0c3341b944c3b23114e4517'"}
{"level":30,"time":1630944876346,"pid":7,"hostname":"n01-d","msg":"Starting at block: 10985486"}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

RequestError: Timeout awaiting 'request' for 5000ms
    at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:956:65)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Timeout.timeoutHandler [as _onTimeout] (/app/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:559:11)
    at processTimers (node:internal/timers:500:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1630959949664,
    socket: 1630959949664,
    lookup: 1630959949666,
    connect: 1630959949743,
    secureConnect: 1630959949820,
    upload: 1630959949820,
    response: undefined,
    end: undefined,
    error: 1630959954665,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 2,
      tcp: 77,
      tls: 77,
      request: 0,
      firstByte: undefined,
      download: undefined,
      total: 5001
    }
  },
  event: 'request'
}
```

**Comment by edd** [comment]
Add README instructions - this will crash if a network error problems, you need to handle that or docker does
