### ISSUE TITLE
Timeout in ethereum event forwarder

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/ethereum-event-forwarder#7]
Some validators seems to have timeout issue throwing uncatched exception.

While it might be just mis-configuration, it might be good to catch these exception, and get a bit more details on what did timeout (at first sight I'd imagine ever the vega core or the ethereum node did timeout).

```
{"level":30,"time":1631474792367,"pid":283219,"hostname":"vega-test1-digitalocean","msg":"LOG_LEVEL: info"}
{"level":30,"time":1631474792367,"pid":283219,"hostname":"vega-test1-digitalocean","msg":"Connecting to Vega GRPC on '127.0.0.1:3002'"}
{"level":30,"time":1631474792380,"pid":283219,"hostname":"vega-test1-digitalocean","msg":"Using public key: 'f804c635409b7281aee346276eabc1f4de9d730077acd61dc23badd1c27dba17'"}
{"level":30,"time":1631474792749,"pid":283219,"hostname":"vega-test1-digitalocean","msg":"Starting at block: 11022945"}
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

RequestError: Timeout awaiting 'request' for 5000ms
    at ClientRequest.<anonymous> (/root/ethereum-event-forwarder/node_modules/got/dist/source/core/index.js:956:65)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.origin.emit (/root/ethereum-event-forwarder/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at Timeout.timeoutHandler [as _onTimeout] (/root/ethereum-event-forwarder/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:559:11)
    at processTimers (node:internal/timers:500:7) {
  name: 'TimeoutError',
  code: 'ETIMEDOUT',
  timings: {
    start: 1631480534328,
    socket: 1631480534329,
    lookup: 1631480534331,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1631480539331,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 2,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 5003
    }
  },
  event: 'request'
}
```

**Comment by jeremyletang** [comment]
I've just got that issue on my own node, also I'm pretty sure the timeout would have been with polling infura as there was no event to send (so no connection to the core required?) at the time.
```
ethfwdr_1  | {"level":10,"time":1631164490543,"pid":1,"hostname":"719b1429dcc7","msg":"Fetching logs from 13189581 to 13189582"}
ethfwdr_1  | node:internal/process/promises:246
ethfwdr_1  |           triggerUncaughtException(err, true /* fromPromise */);
ethfwdr_1  |           ^
ethfwdr_1  |
ethfwdr_1  | RequestError: Timeout awaiting 'request' for 5000ms
ethfwdr_1  |     at ClientRequest.<anonymous> (/app/node_modules/got/dist/source/core/index.js:956:65)
ethfwdr_1  |     at Object.onceWrapper (node:events:514:26)
ethfwdr_1  |     at ClientRequest.emit (node:events:406:35)
ethfwdr_1  |     at ClientRequest.origin.emit (/app/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
ethfwdr_1  |     at TLSSocket.socketErrorListener (node:_http_client:447:9)
ethfwdr_1  |     at TLSSocket.emit (node:events:394:28)
ethfwdr_1  |     at emitErrorNT (node:internal/streams/destroy:157:8)
ethfwdr_1  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
ethfwdr_1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
ethfwdr_1  |     at runNextTicks (node:internal/process/task_queues:65:3)
ethfwdr_1  |     at Timeout.timeoutHandler [as _onTimeout] (/app/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
ethfwdr_1  |     at listOnTimeout (node:internal/timers:559:11)
ethfwdr_1  |     at processTimers (node:internal/timers:500:7) {
ethfwdr_1  |   name: 'TimeoutError',
ethfwdr_1  |   code: 'ETIMEDOUT',
ethfwdr_1  |   timings: {
ethfwdr_1  |     start: 1631164490545,
ethfwdr_1  |     socket: 1631164490545,
ethfwdr_1  |     lookup: 1631164490546,
ethfwdr_1  |     connect: 1631164490627,
ethfwdr_1  |     secureConnect: 1631164490708,
ethfwdr_1  |     upload: 1631164490708,
ethfwdr_1  |     response: undefined,
ethfwdr_1  |     end: undefined,
ethfwdr_1  |     error: 1631164495548,
ethfwdr_1  |     abort: undefined,
ethfwdr_1  |     phases: {
ethfwdr_1  |       wait: 0,
ethfwdr_1  |       dns: 1,
ethfwdr_1  |       tcp: 81,
ethfwdr_1  |       tls: 81,
ethfwdr_1  |       request: 0,
ethfwdr_1  |       firstByte: undefined,
ethfwdr_1  |       download: undefined,
ethfwdr_1  |       total: 5003
ethfwdr_1  |     }
ethfwdr_1  |   },
ethfwdr_1  |   event: 'request'
ethfwdr_1  | }
```

**Comment by emilbayes** [comment]
Closed by https://github.com/vegaprotocol/ethereum-event-forwarder/commit/b97519a5f7ae9c7534ac3bdd38ebe342a875c02f
