### ISSUE TITLE
Error when calling ethereum node

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/ethereum-event-forwarder#8]
An error happen with an event forwardwer being run by validators, seems like the call to infura returns more results than expected, not sure what is the source of this, but could be nice to investigate.

```
/root/ethereum-event-forwarder/node_modules/nanoeth/http.js:29
      const error = new Error(res.body.error.message)
                    ^

Error: query returned more than 10000 results
    at RPC.request (/root/ethereum-event-forwarder/node_modules/nanoeth/http.js:29:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async EthLogIterator._loop (/root/ethereum-event-forwarder/lib/eth-log-iterator.js:69:29) {
  code: -32005
}

```

**Comment by emilbayes** [comment]
Closed by https://github.com/vegaprotocol/ethereum-event-forwarder/commit/b97519a5f7ae9c7534ac3bdd38ebe342a875c02f
